services:
  ncat:
    image: no-code-architects-toolkit:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5711:8080"
    volumes:
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs
    restart: unless-stopped

volumes:
  storage:
    driver: local
  logs:
    driver: local